---
version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - make install
      - make GenerateAWSProfiles | tee "${HOME}/.aws/config"
  build:
    commands:
      - >
        pipenv run make \
          lint \
          deploy
