---
version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - make Install DockerBuildCfnLint
  build:
    commands:
      - pipenv run make Lint SceptreValidateCore SceptreValidateTest
