---
version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - make Pipenv
      - pipenv run make Install
      - mkdir -p "${HOME}/.aws"
      - pipenv run make GenerateECSAWSProfiles | tee "${HOME}/.aws/config"
  build:
    commands:
      - >
        pipenv run make \
          Lint \
          Deploy
