---
extends: default

ignore: |
  .venv
  cloudformation-resource-providers/*/resource-role.yaml
  cloudformation-resource-providers/*/template.yml

rules:
  braces:
    max-spaces-inside: 1
  line-length:
    max: 160
