---
extends: default

ignore: |
  .venv
  cloudformation-resource-providers/*/resource-role.yaml
  cloudformation-resource-providers/*/template.yml
  **/.aws-sam/build/template.yaml
  **/SAM/*/template.cfn.yaml

rules:
  braces:
    max-spaces-inside: 1
  comments:
    min-spaces-from-content: 1
  line-length:
    max: 220
