---
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Little Orange CloudFormation Custom Resource for creating a member account invite in master Security Hub account
  and then accept from member account
Resources:
  CloudFormationCustomResourceFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: CloudFormation Custom Resource that creates and accepts a member Security Hub account invite
      CodeUri: ./src
      Handler: app.handler
      MemorySize: 128
      Runtime: python3.8
      Role: !GetAtt Role.Arn
      Timeout: 30

  CloudFormationCustomResourcePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt CloudFormationCustomResourceFunction.Arn
      Principal: cloudformation.amazonaws.com

  Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Path: /LittleOrange/
      Policies:
        - PolicyName: SecurityHub
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - iam:GetRole
                  - iam:CreateServiceLinkedRole
                  - organizations:DescribeAccount
                  - securityhub:AcceptInvitation
                  - securityhub:CreateMembers
                  - securityhub:DeclineInvitations
                  - securityhub:DeleteInvitations
                  - securityhub:DeleteMembers
                  - securityhub:DescribeHub
                  - securityhub:DisableSecurityHub
                  - securityhub:DisassociateFromMasterAccount
                  - securityhub:DisassociateMembers
                  - securityhub:EnableSecurityHub
                  - securityhub:GetInvitationsCount
                  - securityhub:GetMasterAccount
                  - securityhub:GetMembers
                  - securityhub:InviteMembers
                  - securityhub:ListInvitations
                  - securityhub:ListMembers
                  - securityhub:ListTagsForResource
                  - securityhub:TagResource
                  - securityhub:UntagResource
                  - securityhub:UpdateSecurityHubConfiguration
                Resource: "*"
              - Sid: AccessOrganizationAccounts
                Effect: Allow
                Action: sts:AssumeRole
                Resource: arn:aws:iam::*:role/OrganizationAccountAccessRole
        - PolicyName: CloudWatchLogs
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"

Outputs:
  ServiceToken:
    Value: !GetAtt CloudFormationCustomResourceFunction.Arn
