---
template_path: Networking/ServiceCatalogPortfolio.cfn.yaml
parameters:
  OrganizationId: !stack_output Core/Organization.yaml::OrganizationId
  OrganizationRootId: !stack_output Core/Organization.yaml::RootId
  ProductS3URLMinimalVPCv1: !UploadS3
    Bucket: littleorange-sam-deployment-resources
    Content: !file_contents "{{ project_path }}/templates/Networking/MinimalVPC.cfn.yaml"
    Key: Sceptre/Networking/MinimalVPC
  ServiceCatalogOrganizationPortfolioShareServiceToken: !stack_output Core/ServiceCatalogOrganizationPortfolioShare.yaml::ServiceToken
  StackTemplateURL: !UploadS3
    Bucket: littleorange-sam-deployment-resources
    Content: !file_contents "{{ project_path }}/templates/Networking/ServiceCatalogPortfolioRole.cfn.yaml"
    Key: Sceptre/Networking/ServiceCatalogPortfolioRole
