---
# 2.2.2 CloudFormation Macro Proxy
template_path: Networking/VPCMacroProxiedStackSets.cfn.yaml
dependencies:
  - Core/Networking/VPCMacro.yaml
parameters:
  OrganizationRootId: !stack_output Core/Organization.yaml::RootId
  Regions: "{{ var.enabled_regions | join(',') }}"
  StackTemplate: !file_contents "{{ project_path }}/templates/Networking/VPCMacroProxied.cfn.yaml"
