---
AWSTemplateFormatVersion: "2010-09-09"
Description: Little Orange GuardDuty Main
Parameters:
  DetectorId:
    Default: NONE
    Description: ID of existing GuardDuty Detector created by enabling Organization Admin account
    Type: String
  GuardDutyOrganizationConfigurationServiceToken:
    Description: Service Token for CloudFormation Custom Resource
    Type: String
Conditions:
  CreateDetector: !Equals [!Ref DetectorId, NONE]
Resources:
  GuardDutyDetector:
    Condition: CreateDetector # enabling a GuardDuty Organization Admin account auto-creates a Detector that cannot be deleted
    Type: AWS::GuardDuty::Detector
    Properties:
      DataSources:
        S3Logs:
          Enable: true
      Enable: true
      FindingPublishingFrequency: ONE_HOUR

  GuardDutyOrganizationConfiguration:
    Type: Custom::GuardDutyOrganizationConfiguration
    Properties:
      ServiceToken: !Ref GuardDutyOrganizationConfigurationServiceToken
      OrganizationConfiguration:
        DetectorId: !If [CreateDetector, !Ref GuardDutyDetector, !Ref DetectorId]
        AutoEnable: true
        DataSources:
          S3Logs:
            AutoEnable: true
