---
AWSTemplateFormatVersion: "2010-09-09"
Description: 2.2.1 Little Orange Custom Resource Proxy Stack Set
Parameters:
  AllowedRoleName:
    Description: Role name to allow to publish to the SNS topic of the Custom Resource Proxy to enable cross-account use
    Type: String
  OrganizationId:
    Description: Organization ID to use to allow access to the SNS topic of the Custom Resource Proxy
    Type: String
  Regions:
    Description: AWS Regions to deploy Stack Set to
    Type: CommaDelimitedList
  StackTemplateURL:
    Description: S3 URL of uploaded CloudFormation template to deploy in set
    Type: String
Resources:
  StackSet:
    Type: AWS::CloudFormation::StackSet
    Properties:
      Capabilities:
        - CAPABILITY_IAM
      Description: CloudFormation Custom Resource Proxy
      Parameters:
        - ParameterKey: AllowedRoleName
          ParameterValue: !Ref AllowedRoleName
        - ParameterKey: OrganizationId
          ParameterValue: !Ref OrganizationId
      PermissionModel: SELF_MANAGED
      StackInstancesGroup:
        - DeploymentTargets:
            Accounts:
              - !Ref "AWS::AccountId"
          Regions: !Ref Regions
      StackSetName: !Sub "${AWS::StackName}"
      TemplateURL: !Ref StackTemplateURL
