---
AWSTemplateFormatVersion: "2010-09-09"
Description: Little Orange Custom Resource Proxy Stack Set
Parameters:
  StackTemplate:
    Description: Stack template to deploy in set
    Type: String
Resources:
  StackSet:
    Type: AWS::CloudFormation::StackSet
    Properties:
      Capabilities:
        - CAPABILITY_IAM
      Description: CloudFormation Custom Resource Proxy
      PermissionModel: SELF_MANAGED
      StackInstancesGroup:
        - DeploymentTargets:
            Accounts:
              - !Ref "AWS::AccountId"
          Regions:
            - ap-northeast-1
            - ap-northeast-2
            - ap-south-1
            - ap-southeast-1
            - ap-southeast-2
            - ca-central-1
            - eu-central-1
            - eu-north-1
            - eu-west-1
            - eu-west-2
            - eu-west-3
            - sa-east-1
            - us-east-1
            - us-east-2
            - us-west-1
            - us-west-2
      StackSetName: !Sub "${AWS::StackName}"
      TemplateBody: !Ref StackTemplate
