---
AWSTemplateFormatVersion: "2010-09-09"
Description: Little Orange GuardDuty in Organization Master
Parameters:
  GuardDutyOrganizationServiceToken:
    Description: Service Token for CloudFormation Custom Resource
    Type: String
  GuardDutyAdminAccountId:
    AllowedPattern: "[0-9]{12}"
    Description: Account ID for the account to enable as GuardDuty Organization Admin
    Type: String
Resources:
  GuardDutyDetector:
    Type: AWS::GuardDuty::Detector
    Properties:
      DataSources:
        S3Logs:
          Enable: true
      Enable: true

  GuardDutyOrganization:
    Type: Custom::GuardDutyOrganization
    DependsOn: [GuardDutyDetector]
    Properties:
      ServiceToken: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:LittleOrangeCustomResourceProxy"
      CustomResourceProperties:
        ServiceToken: !Ref GuardDutyOrganizationServiceToken
        AccountId: !Ref GuardDutyAdminAccountId
        OrganizationConfiguration:
          AutoEnable: true
          DataSources:
            S3Logs:
              AutoEnable: true
        Region: !Ref "AWS::Region"
