---
AWSTemplateFormatVersion: "2010-09-09"
Description: Little Orange GuardDuty deploy in all regions
Parameters:
  GuardDutyOrganizationServiceToken:
    Description: Service Token for CloudFormation Custom Resource
    Type: String
  GuardDutyAdminAccountId:
    AllowedPattern: "[0-9]{12}"
    Description: Account ID for the account to enable as GuardDuty Organization Admin
    Type: String
  Regions:
    Description: AWS Regions to deploy Stack Set to
    Type: CommaDelimitedList
  StackTemplate:
    Description: Stack template to deploy in set
    Type: String
Resources:
  GuardDutyStackSet:
    Type: AWS::CloudFormation::StackSet
    Properties:
      Description: Deploy GuardDuty in all regions
      Parameters:
        - ParameterKey: GuardDutyOrganizationServiceToken
          ParameterValue: !Ref GuardDutyOrganizationServiceToken
        - ParameterKey: GuardDutyAdminAccountId
          ParameterValue: !Ref GuardDutyAdminAccountId
      PermissionModel: SELF_MANAGED
      StackInstancesGroup:
        - DeploymentTargets:
            Accounts:
              - !Ref "AWS::AccountId"
          Regions: !Ref Regions
      StackSetName: !Sub "${AWS::StackName}"
      TemplateBody: !Ref StackTemplate
