AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Little Orange CloudFormation Custom Resource for update Organization
  configuration for GuardDuty
Resources:
  CloudFormationCustomResourceFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: CloudFormation Custom Resource that runs GuardDuty UpdateOrganizationConfiguration
      CodeUri: s3://littleorange-sam-deployment-resources/e13a57df72ec3c70da2a1c2c7e5bedd2
      Handler: app.handler
      MemorySize: 128
      Runtime: python3.8
      Role:
        Fn::GetAtt:
        - Role
        - Arn
      Timeout: 30
  CloudFormationCustomResourcePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
        - CloudFormationCustomResourceFunction
        - Arn
      Principal: cloudformation.amazonaws.com
  Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
      Path: /LittleOrange/
      Policies:
      - PolicyName: GuardDutyOrganizations
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action:
            - guardduty:UpdateOrganizationConfiguration
            - organizations:DescribeOrganization
            - organizations:ListAWSServiceAccessForOrganization
            - iam:GetRole
            - iam:CreateServiceLinkedRole
            Resource: '*'
      - PolicyName: CloudWatchLogs
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: '*'
Outputs:
  ServiceToken:
    Value:
      Fn::GetAtt:
      - CloudFormationCustomResourceFunction
      - Arn
