---
AWSTemplateFormatVersion: 2010-09-09
Description: Little Orange VPC for DNS
Transform: NetworkingVPC
Metadata:
  cfn-lint:
    config:
      ignore_checks:
        - E3001
Parameters:
  VpcCidr:
    Description: IPv4 CIDR to provision for the VPC
    Type: String
Resources:
  Vpc:
    Type: LittleOrange::Networking::VPC
    Properties:
      AvailabilityZones: 3
      CIDR: !Ref VpcCidr
      InternetGateway: false
      NATGateways: false
      Tiers:
        - Name: Public
          Size: 0.125
        - Name: Private
          Size: 0.5
        - Name: Restricted
          Size: 0.125
        - Name: Networking
          Size: 0.25
