---
AWSTemplateFormatVersion: 2010-09-09
Description: Little Orange IP Ranges
Parameters:
  LittleOrangeCidr:
    Description: IPv4 CIDR of the Little Orange network
    Type: String
  ClientVpnCidr:
    Description: IPv4 CIDR of the Little Orange Client VPN endpoints
    Type: String
  OrganizationAccountId:
    Description: ID of the Little Orange Organization management account
    Type: String
  OrganizationId:
    Description: ID of the Little Orange Organization
    Type: String
Resources:
  PrefixList:
    Type: AWS::EC2::PrefixList
    Properties:
      AddressFamily: IPv4
      Entries:
        - Cidr: !Ref LittleOrangeCidr
          Description: Little Orange IPv4 CIDR Range
        - Cidr: !Ref ClientVpnCidr
          Description: Little Orange Client VPN IPv4 CIDR Range
      MaxEntries: 20
      PrefixListName: LittleOrangeIpRanges

  PrefixListShare:
    Type: AWS::RAM::ResourceShare
    Properties:
      AllowExternalPrincipals: false
      Name: LittleOrangeIPRanges
      Principals:
        - !Sub arn:aws:organizations::${OrganizationAccountId}:organization/${OrganizationId}
      ResourceArns:
        - !GetAtt PrefixList.Arn
Outputs:
  PrefixListId:
    Description: Prefix List ID of the Little Orange IPv4 CIDR Range
    Value: !Ref PrefixList
