---
AWSTemplateFormatVersion: 2010-09-09
Description: Little Orange Minimal VPC
Transform: NetworkingVPC
Metadata:
  cfn-lint:
    config:
      ignore_checks:
        - E3001
Parameters:
  VPCCIDR:
    Description: The IPv4 CIDR range of the VPC
    Type: String
  AvailabilityZones:
    Description: The number of AZs to deploy subnets for in the VPC
    Type: String
Resources:
  VPC:
    Type: LittleOrange::Networking::VPC
    Properties:
      AvailabilityZones: 
        Ref: AvailabilityZones
      CIDR:
        Ref: VPCCIDR
      InternetGateway: false
      NATGateways: false
