---
AWSTemplateFormatVersion: "2010-09-09"
Description: Little Orange Organizations
Metadata:
  cfn-lint:
    config:
      ignore_checks:
        - E3001 # E3001: Invalid or unsupported Type -- user-defined types from CloudFormation Resource Types
        - E1010 # Invalid GetAtt -- user-defined types from CloudFormation Resource Types
Resources:
  OrganizationsServiceLinkedRole:
    Type: AWS::IAM::ServiceLinkedRole
    Properties:
      AWSServiceName: organizations.amazonaws.com

  Organization:
    DependsOn: [OrganizationsServiceLinkedRole]
    Type: LittleOrange::Organizations::Organization
    Properties:
      EnabledPolicyTypes:
        - Type: SERVICE_CONTROL_POLICY
        - Type: TAG_POLICY
      FeatureSet: ALL

  QuarantineOU:
    Type: LittleOrange::Organizations::OrganizationalUnit
    Properties:
      Name: Quarantine
      ParentId: !GetAtt Organization.RootId
      PolicyIds:
        - !Ref QuarantineSCP

  ServerlessSCP:
    DependsOn: [Organization]
    Type: LittleOrange::Organizations::ServiceControlPolicy
    Properties:
      Content: |
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Action": [
                "dynamodb:*",
                "iam:*",
                "lambda:*",
                "sns:*",
                "sqs:*"
              ],
              "Effect": "Allow",
              "Resource": "*"
            }
          ]
        }
      Description: Access to all services
      Name: Open

  QuarantineSCP:
    DependsOn: [Organization]
    Type: LittleOrange::Organizations::ServiceControlPolicy
    Properties:
      Content: |
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Action": "*",
              "Effect": "Deny",
              "Resource": "*"
            }
          ]
        }
      Description: Deny all services
      Name: Quarantine

Outputs:
  OrganizationId:
    Value: !Ref Organization
  RootId:
    Value: !GetAtt Organization.RootId
