---
AWSTemplateFormatVersion: "2010-09-09"
Description: Little Orange Organizations
Metadata:
  cfn-lint:
    config:
      ignore_checks:
        - E3001 # E3001: Invalid or unsupported Type -- user-defined types from CloudFormation Resource Types
Resources:
  OrganizationsServiceLinkedRole:
    Type: AWS::IAM::ServiceLinkedRole
    Properties:
      AWSServiceName: organizations.amazonaws.com

  Organization:
    DependsOn: [OrganizationsServiceLinkedRole]
    Type: LittleOrange::Organizations::Organization
    Properties:
      FeatureSet: ALL

  ServerlessSCP:
    DependsOn: [Organization]
    Type: LittleOrange::Organizations::ServiceControlPolicy
    Properties:
      Content: |
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Action": [
                "dynamodb:*",
                "iam:*",
                "lambda:*",
                "sns:*",
                "sqs:*"
              ],
              "Effect": "Allow",
              "Resource": "*"
            }
          ]
        }
      Description: Access to all services
      Name: Open

Outputs:
  OrganizationId:
    Value: !Ref Organization
