---
AWSTemplateFormatVersion: "2010-09-09"
Description: Little Orange Config Stack Sets
Parameters:
  ConfigAggregatorAccountId:
    AllowedPattern: "[0-9]{12}"
    Description: Account ID that contains the Config Aggregator
    Type: String
  ConfigS3BucketName:
    Description: S3 Bucket to deliver Config snapshots to
    Type: String
  OrganizationRootId:
    Description: Root ID of the Organization to apply as deployment target
    Type: String
  StackTemplate:
    Description: Stack template to deploy in set
    Type: String
Mappings:
  Configuration:
    StackSets:
      Regions:
        # - ap-northeast-1
        # - ap-northeast-2
        # - ap-south-1
        # - ap-southeast-1
        - ap-southeast-2
        # - ca-central-1
        # - eu-central-1
        # - eu-north-1
        # - eu-west-1
        # - eu-west-2
        # - eu-west-3
        # - sa-east-1
        # - us-east-1
        # - us-east-2
        # - us-west-1
        # - us-west-2
Resources:
  StackSet:
    Type: AWS::CloudFormation::StackSet
    Properties:
      Capabilities:
        - CAPABILITY_NAMED_IAM
      Description: Config deployed across regions of Organization master
      Parameters:
        - ParameterKey: ConfigAggregatorAccountId
          ParameterValue: !Ref ConfigAggregatorAccountId
        - ParameterKey: ConfigS3BucketName
          ParameterValue: !Ref ConfigS3BucketName
        - ParameterKey: MainRegion
          ParameterValue: !Ref "AWS::Region"
      PermissionModel: SELF_MANAGED
      StackInstancesGroup:
        - DeploymentTargets:
            Accounts: [!Ref "AWS::AccountId"]
          Regions: !FindInMap [Configuration, StackSets, Regions]
      StackSetName: !Sub "${AWS::StackName}"
      TemplateBody: !Ref StackTemplate

  OrganizationStackSet:
    Type: AWS::CloudFormation::StackSet
    Properties:
      AutoDeployment:
        Enabled: true
        RetainStacksOnAccountRemoval: true
      Capabilities:
        - CAPABILITY_NAMED_IAM
      Description: Config deployed across Organization
      Parameters:
        - ParameterKey: ConfigAggregatorAccountId
          ParameterValue: !Ref ConfigAggregatorAccountId
        - ParameterKey: ConfigS3BucketName
          ParameterValue: !Ref ConfigS3BucketName
        - ParameterKey: MainRegion
          ParameterValue: !Ref "AWS::Region"
      PermissionModel: SERVICE_MANAGED
      StackInstancesGroup:
        - DeploymentTargets:
            OrganizationalUnitIds: [!Ref OrganizationRootId]
          Regions: !FindInMap [Configuration, StackSets, Regions]
      StackSetName: !Sub "${AWS::StackName}Organization"
      TemplateBody: !Ref StackTemplate
