---
AWSTemplateFormatVersion: "2010-09-09"
Description: Little Orange GuardDuty Stack Set to subscribe existing accounts in all regions
Parameters:
  MasterAccountId:
    AllowedPattern: "[0-9]{12}"
    Description: Account ID of the Organization Master
    Type: String
  MasterAccountEmail:
    Description: Email address associated with the Organization Master
    Type: String
  Regions:
    Description: AWS Regions to deploy Stack Set to
    Type: CommaDelimitedList
  SandboxAccountId:
    AllowedPattern: "[0-9]{12}"
    Description: Account ID of the Organization Sandbox account
    Type: String
  SandboxAccountEmail:
    Description: Email address associated with the Organization Sandbox account
    Type: String
  StackTemplate:
    Description: Stack template to deploy
    Type: String
Resources:
  GuardDutyStackSet:
    Type: AWS::CloudFormation::StackSet
    Properties:
      Description: Subscribe existing accounts to GuardDuty Organization admin account in all regions
      Parameters:
        - ParameterKey: DetectorId
          ParameterValue: /LittleOrange/GuardDuty/DetectorId
        - ParameterKey: MasterAccountEmail
          ParameterValue: !Ref MasterAccountEmail
        - ParameterKey: MasterAccountId
          ParameterValue: !Ref MasterAccountId
        - ParameterKey: SandboxAccountEmail
          ParameterValue: !Ref SandboxAccountEmail
        - ParameterKey: SandboxAccountId
          ParameterValue: !Ref SandboxAccountId
      PermissionModel: SELF_MANAGED
      StackInstancesGroup:
        - DeploymentTargets:
            Accounts:
              - !Ref "AWS::AccountId"
          Regions: !Ref Regions
      StackSetName: !Sub "${AWS::StackName}"
      TemplateBody: !Ref StackTemplate
