---
AWSTemplateFormatVersion: "2010-09-09"
Description: Little Orange Security Hub
Parameters:
  DeploySecurityHubMasterResources:
    Description: "TRUE to deploy Security Hub resources if this stack is within the Security Hub master account, FALSE to not deploy"
    Type: String
  OrganizationMasterAccountId:
    AllowedPattern: "[0-9]{12}"
    Description: Account ID for the Organization master account to invoke Custom Resource Proxy
    Type: String
  SecurityHubMasterAccountId:
    AllowedPattern: "[0-9]{12}"
    Description: Account ID for the account to Deploy as master Security Hub account
    Type: String
  SecurityHubOnboardingServiceToken:
    Description: Service Token for CloudFormation Custom Resource to onboard accounts to master Security Hub
    Type: String
Conditions:
  IsSecurityHubMasterAccount: !Equals [!Ref "AWS::AccountId", !Ref SecurityHubMasterAccountId]
  DeploySecurityHubResources: !Or
    - !Not [Condition: IsSecurityHubMasterAccount]
    - !Equals [!Ref DeploySecurityHubMasterResources, "TRUE"]
  OnboardSecurityHub: !Not [Condition: IsSecurityHubMasterAccount]
Resources:
  Hub:
    Condition: DeploySecurityHubResources
    Type: AWS::SecurityHub::Hub
    Properties: {}

  Onboarding: # invoke onboarding Custom Resource via proxy
    Condition: OnboardSecurityHub
    Type: Custom::SecurityHubOnboarding
    Properties:
      ServiceToken: !Sub "arn:aws:sns:${AWS::Region}:${OrganizationMasterAccountId}:LittleOrangeCustomResourceProxy"
      CustomResourceProperties:
        ServiceToken: !Ref SecurityHubOnboardingServiceToken
        AccountId: !Ref "AWS::AccountId"
        MasterAccountId: !Ref SecurityHubMasterAccountId
        Region: !Ref "AWS::Region"
