---
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Little Orange Transit Gateway Route Manager
Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Description: Manages CloudFormation stacks for Transit Gateway Attachments route table associations and propagation
      CodeUri: ./src
      Handler: app.handler
      MemorySize: 128
      Runtime: python3.8
      Role: !GetAtt Role.Arn
      Timeout: 120

  CloudFormationCustomResourcePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt CloudFormationCustomResourceFunction.Arn
      Principal: events.amazonaws.com

  Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Path: /LittleOrange/
      Policies:
        - PolicyName: AssumeCrossAccountRole
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action: iam:AssumeRole
                Resource: arn:aws:iam::*:role/LittleOrange/TransitGatewayRouteManagerRole
        - PolicyName: ManageRouteManagerStacks
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action: cloudformation:DescribeStacks
                Resource: '*'
              - Effect: Allow
                Action: cloudformation:*Stack
                Resource: !Sub arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/TransitGatewayRouteManager-*
              - Effect: Allow
                Action:
                  - ec2:AssociateTransitGatewayRouteTable
                  - ec2:DeleteTransitGatewayRoute
                  - ec2:DescribeTransitGatewayAttachments
                  - ec2:DescribeTransitGatewayRouteTables
                  - ec2:DescribeTransitGateways
                  - ec2:DisableTransitGatewayRouteTablePropagation
                  - ec2:DisassociateTransitGatewayRouteTable
                  - ec2:EnableTransitGatewayRouteTablePropagation
                  - ec2:GetTransitGatewayRouteTableAssociations
                  - ec2:GetTransitGatewayRouteTablePropagations
                  - ec2:ReplaceTransitGatewayRoute
                  - ec2:SearchTransitGatewayMulticastGroups
                  - ec2:SearchTransitGatewayRoutes
                Resource: '*'
        - PolicyName: CloudWatchLogs
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"

Outputs:
  ServiceToken:
    Value: !GetAtt CloudFormationCustomResourceFunction.Arn
