---
template_path: Networking/Route53Resolver.cfn.yaml
parameters:
  DnsVpcId: !stack_output Networking/DNSVPC.yaml::VpcId
  IpRangesPrefixListId: !stack_output Networking/IPRanges.yaml::PrefixListId
  OrganizationAccountId: !stack_output Core/Organization.yaml::MasterAccountId
  OrganizationId: !stack_output Core/Organization.yaml::OrganizationId
  ResolverEndpointSubnetIds: !stack_output Networking/DNSVPC.yaml::VpcPrivateSubnetIds
  Route53ResolverEndpointExtendedOutputServiceToken: !stack_output Networking/Route53ResolverEndpointExtendedOutput.yaml::ServiceToken
