---
AWSTemplateFormatVersion: "2010-09-09"
Description: 1.5 Little Orange GitHub Credentials
Parameters:
  GitHubUsername:
    Description: Username of the GitHub credentials
    Type: String
  GitHubToken:
    Description: GitHub Personal Access Token (PAT) of user
    NoEcho: true
    Type: String
Resources:
  GithubCodeBuildCredentials:
    Type: AWS::CodeBuild::SourceCredential
    Properties:
      Token: !Ref GitHubToken
      ServerType: GITHUB
      AuthType: PERSONAL_ACCESS_TOKEN

  GitHubCredentialsSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: /littleorange/github
      SecretString: !Sub |
        {
          "username": "${GitHubUsername}",
          "token": "${GitHubToken}"
        }
