---
AWSTemplateFormatVersion: "2010-09-09"
Description: 1.5 Little Orange DevOps Pipeline
Parameters:
  GitHubUrl:
    Default: https://github.com/tomwwright/littleorange.git
    Description: GitHub Repository URL, e.g. https://github.com/example/example.git
    Type: String
  GitHubBranch:
    Default: master
    Description: PRs against this branch with trigger tests in CodeBuild via webhook
    Type: String
Resources:
  DeployProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: LittleOrangeDeploy
      ServiceRole: !GetAtt Role.Arn
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:3.0
        PrivilegedMode: true
        Type: LINUX_CONTAINER
      Source:
        Type: GITHUB
        Location: !Ref GitHubUrl
        BuildSpec: devops/buildspec/LittleOrangeDeploy.buildspec.yml
      Triggers:
        Webhook: true
        FilterGroups:
          - - Type: EVENT
              Pattern: PUSH
            - Type: HEAD_REF
              Pattern: !Sub "^refs/heads/${GitHubBranch}$"

  PRTestProject: # 1.5.1 Pull Request Validation using CodeBuild
    Type: AWS::CodeBuild::Project
    Properties:
      Name: LittleOrangePRTest
      ServiceRole: !GetAtt Role.Arn
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:3.0
        PrivilegedMode: true
        Type: LINUX_CONTAINER
      Source:
        Type: GITHUB
        Location: !Ref GitHubUrl
        BuildSpec: devops/buildspec/LittleOrangePRTest.buildspec.yml
      Triggers:
        Webhook: true
        FilterGroups:
          - - Type: EVENT
              Pattern: PULL_REQUEST_CREATED,PULL_REQUEST_UPDATED
            - Type: BASE_REF
              Pattern: !Sub "^refs/heads/${GitHubBranch}$"

  Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
      Path: /LittleOrange/
      Policies:
        - PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
          PolicyName: CloudWatchLogs
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess

  SelfManagePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: ManageRole
            Effect: Allow
            Action: iam:*
            Resource: !GetAtt Role.Arn
          - Sid: ManageCodeBuild
            Effect: Allow
            Action: codebuild:*
            Resource:
              - !GetAtt DeployProject.Arn
              - !GetAtt PRTestProject.Arn
          - Sid: ManageStack
            Effect: Allow
            Action: cloudformation:*
            Resource: !Sub arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/${AWS::StackName}/*
      PolicyName: SelfManageStack
      Roles: [!Ref Role]
