---
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Little Orange CloudFormation Custom Resource for managing Cost and Usage Report Definitions https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/cur.html
Resources:
  CloudFormationCustomResourceFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: CloudFormation Custom Resource for managing Cost and Usage Report Definitions
      CodeUri: ./src
      Handler: app.handler
      MemorySize: 128
      Runtime: python3.8
      Role: !GetAtt Role.Arn
      Timeout: 30

  CloudFormationCustomResourcePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt CloudFormationCustomResourceFunction.Arn
      Principal: cloudformation.amazonaws.com

  Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Path: /LittleOrange/
      Policies:
        - PolicyName: CostAndUsageReports
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - cur:DeleteReportDefinition
                  - cur:DescribeReportDefinitions
                  - cur:ModifyReportDefinition
                  - cur:PutReportDefinition
                Resource: "*"
        - PolicyName: CloudWatchLogs
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"

Outputs:
  ServiceToken:
    Value: !GetAtt CloudFormationCustomResourceFunction.Arn
