---
template_path: Core/CloudFormationMacroProxyStackSet.cfn.yaml
parameters:
  Regions: "{{ var.enabled_regions | join(',') }}"
  StackTemplateURL: !UploadS3
    Bucket: littleorange-sam-deployment-resources
    Content: !Command python sam/CloudFormationMacroProxy/CloudFormationMacroProxy.py
    Key: Sceptre/CloudFormationMacroProxy
