---
# 2.2.3 CloudFormation Self-Managed Roles using CloudFormation Stack Sets
template_path: Core/CloudFormationRolesStackSet.cfn.yaml
parameters:
  MasterAccountId: !stack_output Core/Organization.yaml::MasterAccountId
  OrganizationRootId: !stack_output Core/Organization.yaml::RootId
  SecurityAccountId: !stack_output Core/Organization.yaml::SecurityAccountId
  StackTemplate: !file_contents "{{ project_path }}/templates/Core/CloudFormationRoles.cfn.yaml"
