---
# 2.3.1 CloudFormation Custom Resource for Cost and Usage Report Definitions
template_path: BuildSAM.py
dependencies:
  - Core/SAMDeploymentResources.yaml
sceptre_user_data:
  SAMProject: CostUsageReportDefinition
