---
template_path: Core/EmailDomain.cfn.yaml
parameters:
  DomainName: "{{ var.public_domain }}"
  SESDomainIdentityServiceToken: !stack_output Core/SESDomainIdentity.yaml::ServiceToken
region: us-east-1
