---
# 3.1.1 CloudFormation Custom Resource for Organizations CloudTrail Support
template_path: BuildSAM.py
dependencies:
  - Core/SAMDeploymentResources.yaml
sceptre_user_data:
  SAMProject: EnableIsOrganizationTrail
