---
template_path: Core/GuardDutyStackSet.cfn.yaml
dependencies:
  - Core/CloudFormationRoles.yaml
  - Core/CustomResourceProxy.yaml
parameters:
  GuardDutyAdminAccountId: !stack_output Core/Organization.yaml::SecurityAccountId
  GuardDutyOrganizationServiceToken: !stack_output Core/GuardDutyOrganization.yaml::ServiceToken
  StackTemplate: !file_contents "{{ project_path }}/templates/Core/GuardDuty.cfn.yaml"
