---
template_path: IAM/SAMLFederatedIdentityStackSets.cfn.yaml
parameters:
  IAMSAMLProviderServiceToken: !stack_output Core/IAMSAMLProvider.yaml::ServiceToken
  OrganizationRootId: !stack_output Core/Organization.yaml::RootId
  SAMLIdentityProviderMetadataUrl: "{{ var.federated_identity_saml_metadata_url }}"
  StackTemplateUrl: !UploadS3
    Bucket: littleorange-sam-deployment-resources
    Content: !file_contents "{{ project_path }}/templates/IAM/SAMLFederatedIdentity.cfn.yaml"
    Key: Sceptre/SAMLFederatedIdentity
