---
template_path: IAM/SAMLFederatedIdentityStackSets.cfn.yaml
parameters:
  IAMSAMLProviderServiceToken: !stack_output Core/IAMSAMLProvider.yaml::ServiceToken
  OrganizationRootId: !stack_output Core/Organization.yaml::RootId
  SAMLIdentityProviderMetadataUrl: https://login.microsoftonline.com/614dfa03-04ae-4b58-a783-f27b940e4399/federationmetadata/2007-06/federationmetadata.xml?appid=060fad48-bb2a-4693-86e9-57269217a117
  StackTemplateUrl: !UploadS3
    Bucket: littleorange-sam-deployment-resources
    Content: !file_contents "{{ project_path }}/templates/IAM/SAMLFederatedIdentity.cfn.yaml"
    Key: Sceptre/SAMLFederatedIdentity
