---
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Little Orange CloudFormation Macro for LittleOrange::Networking::VPC Resource
Resources:
  CloudFormationMacroFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: CloudFormation Macro for LittleOrange::Networking::VPC Resource
      CodeUri: ./src
      Handler: macro.app.handler
      MemorySize: 128
      Runtime: python3.8
      Role: !GetAtt Role.Arn
      Timeout: 30

  CloudFormationMacroPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt CloudFormationMacroFunction.Arn
      Principal: cloudformation.amazonaws.com

  Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Path: /LittleOrange/
      Policies:
        - PolicyName: CloudWatchLogs
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"

  Parameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: Lambda ARN for the NetworkingVPC Macro for calling from Macro Proxy
      Name: /LittleOrange/CloudFormation/Macro/NetworkingVPC
      Type: String
      Value: !GetAtt CloudFormationMacroFunction.Arn

Outputs:
  FunctionArn:
    Value: !GetAtt CloudFormationMacroFunction.Arn
