---
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: 3.1.1 Little Orange CloudFormation Custom Resource for enabling IsOrganizationTrail on a CloudTrail trail
Resources:
  CloudFormationCustomResourceFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: CloudFormation Custom Resource that enables IsOrganizationTrail on a CloudTrail trail
      CodeUri: ./src
      Handler: app.handler
      MemorySize: 128
      Runtime: python3.8
      Role: !GetAtt Role.Arn
      Timeout: 30

  CloudFormationCustomResourcePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt CloudFormationCustomResourceFunction.Arn
      Principal: cloudformation.amazonaws.com

  Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Path: /LittleOrange/
      Policies:
        - PolicyName: CloudTrail
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - cloudtrail:UpdateTrail
                  - organizations:DescribeOrganization
                  - organizations:ListAWSServiceAccessForOrganization
                  - iam:GetRole
                  - iam:CreateServiceLinkedRole
                Resource: "*"
        - PolicyName: CloudWatchLogs
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"

Outputs:
  ServiceToken:
    Value: !GetAtt CloudFormationCustomResourceFunction.Arn
